name: Python application test with Github Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Compile C++ code
      run: |
        bash compile_one.sh; rm one.so
    - name: Build Python One module
      run: |
        bash build_one.sh
    - name: Run Tests
      run: |
        pytest
